import { Asset } from 'expo-asset';

export const Logos: { [key: number]: string; } = {
    0: Asset.fromModule(require('../../assets/images/team_logos/0.svg')).uri,
    1: Asset.fromModule(require('../../assets/images/team_logos/1.svg')).uri,
    2: Asset.fromModule(require('../../assets/images/team_logos/2.svg')).uri,
    3: Asset.fromModule(require('../../assets/images/team_logos/3.svg')).uri,
    4: Asset.fromModule(require('../../assets/images/team_logos/4.svg')).uri,
    5: Asset.fromModule(require('../../assets/images/team_logos/5.svg')).uri,
    6: Asset.fromModule(require('../../assets/images/team_logos/6.svg')).uri,
    7: Asset.fromModule(require('../../assets/images/team_logos/7.svg')).uri,
    8: Asset.fromModule(require('../../assets/images/team_logos/8.svg')).uri,
    9: Asset.fromModule(require('../../assets/images/team_logos/9.svg')).uri,
    10: Asset.fromModule(require('../../assets/images/team_logos/10.svg')).uri,
    11: Asset.fromModule(require('../../assets/images/team_logos/11.svg')).uri,
    12: Asset.fromModule(require('../../assets/images/team_logos/12.svg')).uri,
    13: Asset.fromModule(require('../../assets/images/team_logos/13.svg')).uri,
    14: Asset.fromModule(require('../../assets/images/team_logos/14.svg')).uri,
    15: Asset.fromModule(require('../../assets/images/team_logos/15.svg')).uri,
    16: Asset.fromModule(require('../../assets/images/team_logos/16.svg')).uri,
    17: Asset.fromModule(require('../../assets/images/team_logos/17.svg')).uri,
    18: Asset.fromModule(require('../../assets/images/team_logos/18.svg')).uri,
    19: Asset.fromModule(require('../../assets/images/team_logos/19.svg')).uri,
    20: Asset.fromModule(require('../../assets/images/team_logos/20.svg')).uri,
    21: Asset.fromModule(require('../../assets/images/team_logos/21.svg')).uri,
    22: Asset.fromModule(require('../../assets/images/team_logos/22.svg')).uri,
    23: Asset.fromModule(require('../../assets/images/team_logos/23.svg')).uri,
    24: Asset.fromModule(require('../../assets/images/team_logos/24.svg')).uri,
    25: Asset.fromModule(require('../../assets/images/team_logos/25.svg')).uri,
    26: Asset.fromModule(require('../../assets/images/team_logos/26.svg')).uri,
    27: Asset.fromModule(require('../../assets/images/team_logos/27.svg')).uri,
    28: Asset.fromModule(require('../../assets/images/team_logos/28.svg')).uri,
    29: Asset.fromModule(require('../../assets/images/team_logos/29.svg')).uri,
    30: Asset.fromModule(require('../../assets/images/team_logos/30.svg')).uri
}
